### ISSUE TITLE
Allow env variables in config-xpui.ini

### ISSUE THREAD

**Issue by eye-wave** [spicetify/spicetify-cli#2668]
### 📝 Provide a description of the new feature

Main use case would be to write spotify_path like this:
```toml
[Setting]
spotify_path = "$HOME/.local/share/flatpak/ . . . "

``` 
so that, sharing a config with someone else becomes easier.
