### ISSUE TITLE
separate spicetify menu items from spotify ones

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2900]
### 📝 Provide a description of the new feature

for example:
- check through list of all ul items 
- pick out the one containing an svg with aria-label External link
- append `vvMORUKtQKpQcpQ992bR` classname to its button

### ➕ Additional Information

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/b17b43b9-fda1-4526-b5f6-ed0b450cbaa9)

**Comment by sanoojes** [comment]
what about adding this it will select accont and add a border top to it 

```css
.main-contextMenu-menuItem button[role="menuitem"]:has(svg):before {
    content:"";
    width: 100%;
    position: absolute;
    top: 0;
    left:0;
    border-top: 1px solid rgba(var(--spice-rgb-selected-row), .1);
}
```
